<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Barcode.cs" />
    <Compile Remove="BarcodeHelper.cs" />
    <Compile Remove="Types.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShowcaseLibrary\ShowcaseLibrary.csproj" />
  </ItemGroup>

</Project>
